env:
  CIRRUS_CLONE_DEPTH: 3 # The internal git client reads CIRRUS_CLONE_DEPTH.
  LIBPCAP_GIT: https://github.com/the-tcpdump-group/libpcap.git

freebsd_task:
  name: freebsd-amd64
  only_if: $CIRRUS_BRANCH != 'coverity_scan'
  freebsd_instance:
    # FreeBSD fails to start with 1 GB. 8 CPUs max concurrency.
    matrix:
      - image_family: freebsd-11-4
        cpu: 2
        memory: 2G
      - image_family: freebsd-12-2
        cpu: 2
        memory: 2G
      - image_family: freebsd-13-0
        # This one is much slower than the others.
        cpu: 4
        memory: 4G
  env:
    IGNORE_OSVERSION: yes
    MAKEFLAGS: -j 4
    MATRIX_CC: clang gcc10
  script:
    - pkg install -qy git autoconf gcc10
    - pkg install -qy bash cmake # for build_matrix.sh and build.sh
    - pkg install -qy pkgconf # for cmake, replaces pkg-config
    - echo '$ git clone [...] libpcap.git'
    - git -C .. clone --depth ${CIRRUS_CLONE_DEPTH} --branch=master --quiet ${LIBPCAP_GIT}
    - ./build_matrix.sh

linux_task:
  name: linux-amd64
  only_if: $CIRRUS_BRANCH != 'coverity_scan'
  container:
    # Linux works just fine with 1 GB. 16 CPUs max concurrency.
    cpu: 4
    memory: 1G
    image: ubuntu:20.04
  env:
    DEBIAN_FRONTEND: noninteractive
    MAKEFLAGS: -j 5
    matrix:
      - MATRIX_CC: gcc
      - MATRIX_CC: clang
  script:
    - apt-get -qy update
    - apt-get -qy install git autoconf make cmake clang gcc
    - apt-get -qy install flex bison libdbus-1-dev libbluetooth-dev libnl-genl-3-dev libibverbs-dev # for libpcap
    - apt-get -qy install libssl-dev libsmi2-dev libcap-ng-dev libpcap-dev
    - apt list --installed 'lib*-dev'
    - echo '$ git clone [...] libpcap.git'
    - git -C .. clone --depth ${CIRRUS_CLONE_DEPTH} --branch=master --quiet ${LIBPCAP_GIT}
    - ./build_matrix.sh

macos_task:
  name: macos-amd64
  only_if: $CIRRUS_BRANCH != 'coverity_scan'
  macos_instance:
    image: big-sur-xcode
    # "cpu" and "memory" are invalid keywords for macOS tasks now
  env:
    MAKEFLAGS: '-j 12'
  script:
    - brew update >/dev/null
    - brew install libsmi | grep -v '%'
    - echo '$ git clone [...] libpcap.git'
    - git -C .. clone --depth ${CIRRUS_CLONE_DEPTH} --branch=master --quiet ${LIBPCAP_GIT}
    - ./build_matrix.sh

coverity_task:
  name: Coverity Scan
  only_if: $CIRRUS_BRANCH == 'coverity_scan'
  container:
    cpu: 4
    memory: 2G
    image: ubuntu:20.04
  env:
    DEBIAN_FRONTEND: noninteractive
    MAKEFLAGS: -j 5
    COVERITY_SCAN_PROJECT_NAME: $CIRRUS_REPO_FULL_NAME
    COVERITY_SCAN_TOKEN: ENCRYPTED[1b6f994cabfe74267ce2dce81fd9e49f694e9cfe69fb99f7d1580907bec1266efd7b38df3a47ccab53d5af98636f8e9c]
    COVERITY_SCAN_BUILD_COMMAND_PREPEND: ./configure
    COVERITY_SCAN_BUILD_COMMAND: make
    COVERITY_SCAN_BRANCH_PATTERN: $CIRRUS_BRANCH
    TRAVIS_BRANCH: $CIRRUS_BRANCH
    TRAVIS_PULL_REQUEST: ${CIRRUS_BASE_BRANCH:+true}
  script:
    - apt-get -qy update
    - apt-get -qy install autoconf make gcc
    - apt-get -qy install libssl-dev libsmi2-dev libcap-ng-dev libpcap-dev
    - apt-get -qy install git curl wget ruby rubygems ruby-json # for the coverity script
    - apt list --installed 'lib*-dev'
    - ./.travis-coverity-scan-build.sh
