#!/usr/bin/env python3
#
# Copyright (c) 2026 The Tcpdump Group
# All rights reserved.
# SPDX-License-Identifier: BSD-2-Clause
#
# Generate unicode-tables.h, the code point classification tables used
# by the UTF-8 output policy in utf8.c.  The tables are generated from
# the Unicode Character Database that ships with the Python interpreter
# (unicodedata module), so the Unicode version is pinned by the
# interpreter used to run this script and recorded in the output.
#
# Usage: python3 gen-unicode-tables.py > unicode-tables.h
#
# The policy encoded here is deliberately an allowlist:
#
#  - "graphic" code points are displayed as a standalone glyph that
#    occupies one or two terminal columns.  These are the letters,
#    marks that take up space (Mc), numbers, punctuation and symbols,
#    minus everything that is invisible or changes the rendering of
#    its neighbours.
#
#  - "combining" code points (Mn, Me) never stand alone; they may be
#    attached to a preceding graphic glyph, up to a small limit.
#
#  - "wide" code points are the graphic code points with an East Asian
#    Width of Wide (W) or Fullwidth (F); they occupy two columns.
#    Ambiguous (A) width code points are treated as one column.
#
#  - Everything else is rejected and displayed as a "." per byte:
#    controls (Cc), format characters (Cf, e.g. bidi controls and zero
#    width characters), surrogates (Cs), private use (Co), unassigned
#    (Cn), all separators other than U+0020 (Zs, Zl, Zp), and the
#    Default_Ignorable_Code_Point set (invisible "printable" characters
#    such as Hangul fillers and variation selectors).

import sys
import unicodedata

GRAPHIC_CATEGORIES = frozenset((
    "Lu", "Ll", "Lt", "Lm", "Lo",
    "Mc",
    "Nd", "Nl", "No",
    "Pc", "Pd", "Ps", "Pe", "Pi", "Pf", "Po",
    "Sm", "Sc", "Sk", "So",
))
COMBINING_CATEGORIES = frozenset(("Mn", "Me"))

# Default_Ignorable_Code_Point, from DerivedCoreProperties.txt.  The
# unicodedata module does not expose this property, so the ranges are
# listed here.  The set is stable across recent Unicode versions.
DEFAULT_IGNORABLE = (
    (0x00AD, 0x00AD), (0x034F, 0x034F), (0x061C, 0x061C),
    (0x115F, 0x1160), (0x17B4, 0x17B5), (0x180B, 0x180F),
    (0x200B, 0x200F), (0x202A, 0x202E), (0x2060, 0x206F),
    (0x3164, 0x3164), (0xFE00, 0xFE0F), (0xFEFF, 0xFEFF),
    (0xFFA0, 0xFFA0), (0xFFF0, 0xFFF8), (0x1BCA0, 0x1BCA3),
    (0x1D173, 0x1D17A), (0xE0000, 0xE0FFF),
)

# Additional code points that are "graphic" by category but render as
# blank space and are therefore rejected like the separators.
EXTRA_REJECT = (
    (0x2800, 0x2800),  # BRAILLE PATTERN BLANK
)


def in_ranges(cp, ranges):
    return any(first <= cp <= last for first, last in ranges)


def to_ranges(code_points):
    ranges = []
    for cp in sorted(code_points):
        if ranges and ranges[-1][1] == cp - 1:
            ranges[-1][1] = cp
        else:
            ranges.append([cp, cp])
    return ranges


def emit_table(out, name, ranges):
    out.write("static const struct nd_uni_range %s[] = {\n" % name)
    line = ""
    for first, last in ranges:
        item = " { 0x%05X, 0x%05X }," % (first, last)
        if len(line) + len(item) > 72:
            out.write("\t" + line.strip() + "\n")
            line = ""
        line += item
    if line:
        out.write("\t" + line.strip() + "\n")
    out.write("};\n\n")


def main():
    graphic = set()
    combining = set()
    wide = set()
    for cp in range(0x80, 0x110000):
        if in_ranges(cp, DEFAULT_IGNORABLE) or in_ranges(cp, EXTRA_REJECT):
            continue
        ch = chr(cp)
        cat = unicodedata.category(ch)
        if cat in GRAPHIC_CATEGORIES:
            graphic.add(cp)
            if unicodedata.east_asian_width(ch) in ("W", "F"):
                wide.add(cp)
        elif cat in COMBINING_CATEGORIES:
            combining.add(cp)

    out = sys.stdout
    out.write("/*\n"
              " * Generated by gen-unicode-tables.py from the Unicode %s\n"
              " * Character Database.  Do not edit by hand.\n"
              " *\n"
              " * Ranges are inclusive, sorted and non-overlapping.\n"
              " */\n\n" % unicodedata.unidata_version)
    out.write("#define ND_UNICODE_VERSION \"%s\"\n\n" % unicodedata.unidata_version)
    out.write("struct nd_uni_range {\n\tuint32_t first;\n\tuint32_t last;\n};\n\n")
    emit_table(out, "nd_uni_graphic", to_ranges(graphic))
    emit_table(out, "nd_uni_combining", to_ranges(combining))
    emit_table(out, "nd_uni_wide", to_ranges(wide))


if __name__ == "__main__":
    main()
