#!/usr/bin/env perl

$TCPDUMP = "../tcpdump" if (!($TCPDUMP = $ENV{TCPDUMP_BIN}));

use File::Basename;
use POSIX qw( WEXITSTATUS WIFEXITED);
use lib '.';
use testfuncs;

system("mkdir -p tests/NEW tests/DIFF");

if(@ARGV != 4) {
  print "Usage: TESTonce name input output options\n";
  exit 20;
}

$r = runtest($ARGV[0], $ARGV[1], $ARGV[2], $ARGV[3]);
exit $r >> 8;

